### PR TITLE
Work without shims on ES5

### PR DESCRIPTION
**Pull request by glenjamin**
Tests now pass without ES6 shims on Node 4+

As discussed in #43 - does this reasonable?

### CODE REVIEW

**Comment by glenjamin** [comment]
I've just pushed a second commit that should now work on any ES5 environment without requiring ES6 shims.

The diff is fairly small without making things much worse imo - let me know what you think!

**Comment by glenjamin** [comment]
I've also added some additional detection for when `MapIterator`/`SetIterator` is shimmed to skip the tests which fail.

It's a shame the ES6 Set polyfill uses the same internal name as the ES6 Map one - if they didn't both use `__list__` the same iterator detection you have would work.

**Comment by Xotic750** [comment]
Hi, I have nothing against these changes and will implement them on the next push, which should be this week.

**Comment by glenjamin** [comment]
Awesome, thanks!

**Comment by Xotic750** [comment]
I did not use your pull request but all the changes have been made, except for the changes to the tests. I want to leave them for now in the hope that I can get a change made in es6-shim so that they can be detected. Thanks for your input and I hope all goes well with your project.

**Pull request closed without merging**
